-- Register a VFX8 effect adapter here after including its source.
-- For a game or this demo: include("vfx8/particles.lua") from main.lua.
fx = {}
-- fx[1] = {
--   on_enter = function(quality) end,
--   on_exit = function() end,
--   trigger = function(x, y) end,
--   update = function(dt) end,
--   render_scene = function(draw_scene) draw_scene() end,
--   draw = function() end
-- }
